---
abstract: 'Yet another PPI-based Perl source code stripper'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  Module::Build: 0.3601
  Test::More: 0.98
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Stripper
requires:
  Log::Any: 0
  Moo: 0
  PPI: 0
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perl-Stripper
  repository: http://github.com/sharyanto/perl-Perl-Stripper
version: 0.06
